### ISSUE TITLE
Issues in LocksRs.unlock(...)

### ISSUE THREAD

**Issue by amihaiemil** [sttc/stateful#16]
I think REST methods should **always** return a Response and never be declared void. There is always something to tell the client. 

Right now, this method throws exceptions instead of returning appropriate http statuses (for our client the behaviour is probably the same, but our code can be much cleaner) 

We can 

``return Response.status(HttpURLConnection.HTTP_CONFLICT)
                        .entity(String.format("label doesn't match: %s", match))
                        .build()`` instead of throwing an exception with it.

and we can also ``return Response.ok().build();``in the end, when everything went fine.

**Comment by amihaiemil** [comment]
@yegor256 can you see about this one pls? Thanks

**Comment by amihaiemil** [comment]
@karato can you do something here? Thanks

**Comment by amihaiemil** [comment]
@yegor256 ping

**Comment by amihaiemil** [comment]
@yegor256 Don't forget about this pls

**Comment by karato** [comment]
@yegor256 please pay attention to this issue ([par.21](http://at.teamed.io/policy.html#21))

**Comment by yegor256** [comment]
@amihaiemil maybe you're right, but this project has to be migrated to Takes framework and all JAX-RS bugs will just disappear
