### ISSUE TITLE
migrate to Dokku

### ISSUE THREAD

**Issue by yegor256** [sttc/stateful#27]

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) I'm not managing this repo, remove the [webhook](https://github.com/sttc/stateful/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `sttc/stateful` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@rultor release, tag is `1.8.1`

**Comment by 0crat** [comment]
I'm not managing `sttc/stateful` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by yegor256** [comment]
@rultor release, tag is `1.8.2`

**Comment by yegor256** [comment]
@rultor release, tag is `1.8.2`

**Comment by yegor256** [comment]
@rultor release, tag is `1.8.2`
